# Generated by Django 5.1.1 on 2024-09-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='user',
        ),
    ]
